<?php
/**
 * DeleteChatMessagesBulkInputObject
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TextMagic
 *
 * TextMagic REST API
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DeleteChatMessagesBulkInputObject Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeleteChatMessagesBulkInputObject implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DeleteChatMessagesBulkInputObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'inbound_ids' => 'string',
        'sent_ids' => 'string',
        'calls_ids' => 'string',
        'all' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'inbound_ids' => null,
        'sent_ids' => null,
        'calls_ids' => null,
        'all' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'inbound_ids' => 'inbound_ids',
        'sent_ids' => 'sent_ids',
        'calls_ids' => 'calls_ids',
        'all' => 'all'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'inbound_ids' => 'setInboundIds',
        'sent_ids' => 'setSentIds',
        'calls_ids' => 'setCallsIds',
        'all' => 'setAll'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'inbound_ids' => 'getInboundIds',
        'sent_ids' => 'getSentIds',
        'calls_ids' => 'getCallsIds',
        'all' => 'getAll'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['inbound_ids'] = isset($data['inbound_ids']) ? $data['inbound_ids'] : null;
        $this->container['sent_ids'] = isset($data['sent_ids']) ? $data['sent_ids'] : null;
        $this->container['calls_ids'] = isset($data['calls_ids']) ? $data['calls_ids'] : null;
        $this->container['all'] = isset($data['all']) ? $data['all'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets inbound_ids
     *
     * @return string
     */
    public function getInboundIds()
    {
        return $this->container['inbound_ids'];
    }

    /**
     * Sets inbound_ids
     *
     * @param string $inbound_ids Inbound messages ID(s) to delete. Require when \"all\" equal to 0 (false).
     *
     * @return $this
     */
    public function setInboundIds($inbound_ids)
    {
        $this->container['inbound_ids'] = $inbound_ids;

        return $this;
    }

    /**
     * Gets sent_ids
     *
     * @return string
     */
    public function getSentIds()
    {
        return $this->container['sent_ids'];
    }

    /**
     * Sets sent_ids
     *
     * @param string $sent_ids Sent messages ID(s) to delete. Require when \"all\" equal to 0 (false).
     *
     * @return $this
     */
    public function setSentIds($sent_ids)
    {
        $this->container['sent_ids'] = $sent_ids;

        return $this;
    }

    /**
     * Gets calls_ids
     *
     * @return string
     */
    public function getCallsIds()
    {
        return $this->container['calls_ids'];
    }

    /**
     * Sets calls_ids
     *
     * @param string $calls_ids Calls ID(s) to delete. Require when \"all\" equal to 0 (false).
     *
     * @return $this
     */
    public function setCallsIds($calls_ids)
    {
        $this->container['calls_ids'] = $calls_ids;

        return $this;
    }

    /**
     * Gets all
     *
     * @return bool
     */
    public function getAll()
    {
        return $this->container['all'];
    }

    /**
     * Sets all
     *
     * @param bool $all Default is 0 (false). If set to 1 all the entities will be removed.
     *
     * @return $this
     */
    public function setAll($all)
    {
        $this->container['all'] = $all;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


