<?php
/**
 * SurveyNode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TextMagic
 *
 * TextMagic REST API
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SurveyNode Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SurveyNode implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SurveyNode';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'label' => 'string',
        'body' => 'string',
        'node_type' => 'string',
        'is_end_node' => 'bool',
        'send_delay' => 'int',
        'start_nodes' => 'string[]',
        'end_nodes' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'label' => null,
        'body' => null,
        'node_type' => null,
        'is_end_node' => null,
        'send_delay' => null,
        'start_nodes' => null,
        'end_nodes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'label' => 'label',
        'body' => 'body',
        'node_type' => 'nodeType',
        'is_end_node' => 'isEndNode',
        'send_delay' => 'sendDelay',
        'start_nodes' => 'startNodes',
        'end_nodes' => 'endNodes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'label' => 'setLabel',
        'body' => 'setBody',
        'node_type' => 'setNodeType',
        'is_end_node' => 'setIsEndNode',
        'send_delay' => 'setSendDelay',
        'start_nodes' => 'setStartNodes',
        'end_nodes' => 'setEndNodes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'label' => 'getLabel',
        'body' => 'getBody',
        'node_type' => 'getNodeType',
        'is_end_node' => 'getIsEndNode',
        'send_delay' => 'getSendDelay',
        'start_nodes' => 'getStartNodes',
        'end_nodes' => 'getEndNodes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['label'] = isset($data['label']) ? $data['label'] : null;
        $this->container['body'] = isset($data['body']) ? $data['body'] : null;
        $this->container['node_type'] = isset($data['node_type']) ? $data['node_type'] : null;
        $this->container['is_end_node'] = isset($data['is_end_node']) ? $data['is_end_node'] : null;
        $this->container['send_delay'] = isset($data['send_delay']) ? $data['send_delay'] : null;
        $this->container['start_nodes'] = isset($data['start_nodes']) ? $data['start_nodes'] : null;
        $this->container['end_nodes'] = isset($data['end_nodes']) ? $data['end_nodes'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['label'] === null) {
            $invalidProperties[] = "'label' can't be null";
        }
        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ($this->container['node_type'] === null) {
            $invalidProperties[] = "'node_type' can't be null";
        }
        if ($this->container['is_end_node'] === null) {
            $invalidProperties[] = "'is_end_node' can't be null";
        }
        if ($this->container['send_delay'] === null) {
            $invalidProperties[] = "'send_delay' can't be null";
        }
        if ($this->container['start_nodes'] === null) {
            $invalidProperties[] = "'start_nodes' can't be null";
        }
        if ($this->container['end_nodes'] === null) {
            $invalidProperties[] = "'end_nodes' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string $label label
     *
     * @return $this
     */
    public function setLabel($label)
    {
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string $body body
     *
     * @return $this
     */
    public function setBody($body)
    {
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets node_type
     *
     * @return string
     */
    public function getNodeType()
    {
        return $this->container['node_type'];
    }

    /**
     * Sets node_type
     *
     * @param string $node_type node_type
     *
     * @return $this
     */
    public function setNodeType($node_type)
    {
        $this->container['node_type'] = $node_type;

        return $this;
    }

    /**
     * Gets is_end_node
     *
     * @return bool
     */
    public function getIsEndNode()
    {
        return $this->container['is_end_node'];
    }

    /**
     * Sets is_end_node
     *
     * @param bool $is_end_node is_end_node
     *
     * @return $this
     */
    public function setIsEndNode($is_end_node)
    {
        $this->container['is_end_node'] = $is_end_node;

        return $this;
    }

    /**
     * Gets send_delay
     *
     * @return int
     */
    public function getSendDelay()
    {
        return $this->container['send_delay'];
    }

    /**
     * Sets send_delay
     *
     * @param int $send_delay send_delay
     *
     * @return $this
     */
    public function setSendDelay($send_delay)
    {
        $this->container['send_delay'] = $send_delay;

        return $this;
    }

    /**
     * Gets start_nodes
     *
     * @return string[]
     */
    public function getStartNodes()
    {
        return $this->container['start_nodes'];
    }

    /**
     * Sets start_nodes
     *
     * @param string[] $start_nodes start_nodes
     *
     * @return $this
     */
    public function setStartNodes($start_nodes)
    {
        $this->container['start_nodes'] = $start_nodes;

        return $this;
    }

    /**
     * Gets end_nodes
     *
     * @return string[]
     */
    public function getEndNodes()
    {
        return $this->container['end_nodes'];
    }

    /**
     * Sets end_nodes
     *
     * @param string[] $end_nodes end_nodes
     *
     * @return $this
     */
    public function setEndNodes($end_nodes)
    {
        $this->container['end_nodes'] = $end_nodes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


